language: node_js
node_js: node
before_install:
  - npm install -g webpack gulp
install: true
script:
  - cd adaptive-education-ai
  - npm install
  - gulp scripts
  - gulp assets
  - cd ../frontend
  - npm install
  - webpack
